ordererca.akp.com:
  image: hyperledger/fabric-ca:1.4.4
  container_name: ordererca.akp.com
  ports:
    - "5010:5010"
  environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  volumes:
    - "$PWD:/etc/hyperledger/fabric-ca-server"
  command: sh -c 'fabric-ca-server start -b admin:adminroot'