version: '2'

volumes:
  peer0.orgb.akp.com:
networks:
  fabric144:
services:
  couchdb0.orgb.akp.com:
    container_name: couchdb0.orgb.akp.com
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "10051:5984"
    networks:
      - fabric144

  peer0.orgb.akp.com:
    container_name: peer0.orgb.akp.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.orgb.akp.com:5984
      - CORE_PEER_ID=peer0.orgb.akp.com
      - CORE_PEER_ADDRESS=peer0.orgb.akp.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.orgb.akp.com:9151
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9151
      - CORE_PEER_LOCALMSPID=OrgBMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_fabric144
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/tlscacerts/tlsca-cert.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgb.akp.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgb.akp.com:9051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_PROFILE_ENABLED=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orgb/peer0
    volumes:
        - /var/run:/host/var/run
        - ./../crypto/orgb/msp-peer0:/etc/hyperledger/fabric/msp
        - ./../crypto/orgb/tls-msp-peer0:/etc/hyperledger/fabric/tls
    networks:
      - fabric144
    ports:
      - 9051:9051
