ca.orgb.ceadar.ucd.com:
  image: hyperledger/fabric-ca:1.4.4
  container_name: ca.orgb.ceadar.ucd.com
  ports:
    - "9010:9010"
  environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  volumes:
    - "$PWD:/etc/hyperledger/fabric-ca-server"
  command: sh -c 'fabric-ca-server start -b admin:adminroot'