NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/192-168-0-129-7010.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/192-168-0-129-7010.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/192-168-0-129-7010.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/192-168-0-129-7010.pem
    OrganizationalUnitIdentifier: orderer
