orgbca.ceadar.ucd.com:
  image: hyperledger/fabric-ca:1.4.4
  container_name: orgbca.ceadar.ucd.com
  ports:
    - "7010:7010"
  environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  volumes:
    - "$PWD:/etc/hyperledger/fabric-ca-server"
    - orgbca.ceadar.ucd.com_volume:/etc/hyperledger
  command: sh -c 'fabric-ca-server start -b admin:adminroot'