tlsca.akp.com:
  image: hyperledger/fabric-ca:1.4.4
  container_name: tlsca.akp.com
  ports:
    - "5001:5001"
  environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
  volumes:
    - "$PWD:/etc/hyperledger/fabric-ca-server"
    - tlsca.akp.com_data:/etc/hyperledger/fabric-ca-server
  command: sh -c 'fabric-ca-server start -b admin:adminroot'